version: '3.8'

services:
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PG_USER=postgres
      - PG_PASSWORD=your_password
      - PG_DATABASE=your_database
      - PG_HOST=db
      - PG_PORT=5432
      - ACCESS_TOKEN_SECRET=your_jwt_secret_key
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
