export default interface IOrder {
  accred_commission: string,
  actual_fee: string,
  agent: string,
  agent_signed: string | null,
  agent_subagent_docs_prepared: string,
  airtable_id: string,
  autonumber: string,
  bank_commission: string,
  client: string,
  client_inn: string,
  contractor: string,
  country: string,
  currency: string,
  currency_paid: string | null,
  exchange_rate: string,
  exporter_name: string,
  hidden_rate: string,
  hired: string | null,
  id: number,
  instruction_link: string,
  invoice_issued: boolean,
  invoice_link: string,
  letter_of_credit_opened: boolean,
  letter_of_credit_released: boolean,
  manager: string,
  payment_purpose: string,
  payment_terms: string,
  placement_date: string,
  primary_documents_received: boolean,
  rate_fixation_date: string,
  receipt_number: string,
  registered_in_bank: string | null,
  report_link: string,
  report_signed: boolean,
  request_amount: string,
  request_by_rate: string,
  request_link: string,
  request_number: string,
  reviewer: string,
  sequential_number: string,
  status: string,
  subagent: string,
  subagent_payer: string,
  swift_code: string,
  swift_link: string,
  swift_received: boolean,
  swift_status: string,
  total_amount: string,
  transaction_closed: string | null,
  transaction_type: string,
  with_accreditor: string
}