import { APPLICATIONS_TABLE_ID, APPLICATIONS_FIELDS } from './applications';
import { MANAGERS_TABLE_ID, MANAGERS_FIELDS } from './managers';
import { CONTRACTORS_TABLE_ID, CONTRACTORS_FIELDS } from './contractors';
import { AGENTS_TABLE_ID, AGENTS_FIELDS } from './agents';
import { CLIENTS_TABLE_ID, CLIENTS_FIELDS } from './clients';
import { COUNTRY_TABLE_ID, COUNTRY_FIELDS } from './country';
import { SUBAGENTS_TABLE_ID, SUBAGENTS_FIELDS } from './subagents';
import { SUBAGENT_PAYERS_TABLE_ID, SUBAGENT_PAYERS_FIELDS } from './subagentPayers';

export const TABLES = {
  APPLICATIONS: APPLICATIONS_TABLE_ID,
  MANAGERS: MANAGERS_TABLE_ID,
  CONTRACTORS: CONTRACTORS_TABLE_ID,
  AGENTS: AGENTS_TABLE_ID,
  CLIENTS: CLIENTS_TABLE_ID,
  COUNTRY: COUNTRY_TABLE_ID,
  SUBAGENTS: SUBAGENTS_TABLE_ID,
  SUBAGENT_PAYERS: SUBAGENT_PAYERS_TABLE_ID
} as const;

export const TABLE_NAMES = {
  [TABLES.APPLICATIONS]: 'Applications',
  [TABLES.MANAGERS]: 'Managers',
  [TABLES.CONTRACTORS]: 'Контрагенты',
  [TABLES.AGENTS]: 'Агенты',
  [TABLES.CLIENTS]: 'Клиенты',
  [TABLES.COUNTRY]: 'Страна',
  [TABLES.SUBAGENTS]: 'Субагенты',
  [TABLES.SUBAGENT_PAYERS]: 'Плательщик Субагента'
} as const;

export const FIELD_ORDER = {
  [TABLES.APPLICATIONS]: APPLICATIONS_FIELDS,
  [TABLES.MANAGERS]: MANAGERS_FIELDS,
  [TABLES.CONTRACTORS]: CONTRACTORS_FIELDS,
  [TABLES.AGENTS]: AGENTS_FIELDS,
  [TABLES.CLIENTS]: CLIENTS_FIELDS,
  [TABLES.COUNTRY]: COUNTRY_FIELDS,
  [TABLES.SUBAGENTS]: SUBAGENTS_FIELDS,
  [TABLES.SUBAGENT_PAYERS]: SUBAGENT_PAYERS_FIELDS
} as const;