export default interface IOrder {
  id?: number;
  autonumber: number | null | string;
  status: string | null;
  order_number: number | null | string;
  manager: string | null;
  reviewer: string | null;
  date: string | null;
  date_hired: string | null;
  contragent: string | null;
  agent: string | null;
  client: string | null;
  client_inn: string | null;
  name_agency: string | null;
  swift_code: string | null;
  country: string | null;
  calc_condition: string | null;
  type_transaction: string | null;
  number_receiving: number | null | string;
  date_instruction: string | null;
  currency: string | null;
  vip_condition: string | null;
  sum_order: number | null | string;
  vip_commission: number | null | string;
  hide_commision: number | null | string;
  commision_plus_percent: number | null | string;
  commision_plus_accredit: number | null | string;
  commision_plus_escrow: number | null | string;
  money_rate: number | null | string;
  hide_money_rate: number | null | string;
  date_fixation_rate: string | null;
  order_rate_rub: string | null;
  agency_award: number | null | string;
  real_award: number | null | string;
  not_ours_award: number | null | string;
  sum: number | null | string;
  letter_of_credit: boolean | null | string;
  take_first_doc: boolean | null | string;
  invoice: string | null;
  date_contract_signed: string | null;
  date_reg_bank: string | null;
  date_open_letter_of_credit: string | null;
  date_valet_agency: string | null;
  date_taking_agency: string | null;
  date_paid_rub: string | null;
  date_unhide_letter_of_credit: string | null;
  date_sign_act: string | null;
  date_close_deal: string | null;
  cycle_deal: number | null | string;
  purpose_of_payment: string | null;
  subagent: string | null;
  subagents_payer: string | null;
  serial_num_for_payer: number | null | string;
  date_docs_agent_and_subagent: string | null;
  date_taking_swift: string | null;
  date_get_swift103: string | null;
  date_take_swift103: string | null;
  date_get_swift199: string | null;
  date_take_swift199: string | null;
  date_refund: string | null;
  date_take_refund: string | null;
  status_swift: string | null;
  stuck_money: boolean | null | string;
  stage_problem: string | null;
  comment_problem: string | null;
  stuck_money_name: string | null;
  stuck_money_sum: number | null | string;
  mistake_is_it_name: string | null;
  order_link: string | null;
  invoice_link: string | null;
  assignment_link: string | null;
  swift_link: string | null;
  swift103_link: string | null;
  swift199_link: string | null;
  act_link: string | null;
  money_gone: boolean | null | string;
}