export const STATUS_OPTIONS = [
  '1. chat not created',
  '1\'. chat created',
  '2. received primary documents',
  '3. payer approval',
  '4. agent. agreement signed',
  '5. invoice issued for the payer',
  '6. rate fixed',
  '7. order signed',
  '8. letter of credit opened',
  '9. transferred for payment',
  '10. SWIFT received',
  '11. SWIFT 103 requested',
  '12. SWIFT 103 received',
  '13. SWIFT 199 requested',
  '14. SWIFT 199 received',
  '15. refund',
  '16. re-paid after refund',
  '17`. waiting for currency to arrive at recipient',
  '17. money at recipient',
  '18. agent and subagent agreement signed',
  '19. agent and subagent order signed',
  '20. agent and subagent report act signed',
  'waiting for rubles',
  'received rubles',
  'cancelled by client',
  'application closed',
  'recipient agreed upon (for Export only)',
  'waiting for currency (for Export only)',
  'received currency (for Export only)',
  'transferred rubles for payment (for Export only)',
  'rubles at recipient (for Export only)'
] as const;

export type ApplicationStatus = typeof STATUS_OPTIONS[number];